name: portifolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  video_player: ^2.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/HEY.mp4
    - assets/images/HEY.png
    - assets/images/VOID.png
    - assets/images/Mobileappdeveloper.png
    - assets/images/1728437402614.jpg
    - assets/images/logos/css.png
    - assets/images/logos/dart.png
    - assets/images/logos/flutter.png
    - assets/images/logos/html.png
    - assets/images/logos/lua.png
    - assets/images/logos/github.png
    - assets/images/logos/firebase.png
    - assets/images/logos/figma.png
    - assets/images/screenshots/Screenshot 2025-03-26 112214.png
    - assets/images/screenshots/Screenshot 2025-03-26 112237.png